#!/usr/bin/env python3
"""
ENDO-LUMBAR Study: Switch primary analysis from brms to PyMC.
Updates tables (table2, table3), creates brms sensitivity archive,
generates Figures S9 and S11 (Python/matplotlib).
Figures 2 and 3 are generated by 23b_update_figures_2_3.R (ggplot2).
"""

import os
import csv
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyBboxPatch
from matplotlib.lines import Line2D
import arviz as az
import warnings
warnings.filterwarnings('ignore')

# =============================================================================
# PATHS
# =============================================================================
base = "/Users/cjsogn/ENDO_LUMBAR"
tables = os.path.join(base, "tables")
models = os.path.join(base, "models")
fig_dir = os.path.join(base, "figures")
pub_dir = os.path.join(fig_dir, "publication")
os.makedirs(pub_dir, exist_ok=True)

# =============================================================================
# COLOR PALETTE (matching R scripts)
# =============================================================================
COL_ELD = "#2166AC"
COL_MSD = "#B2182B"
COL_GRAY = "#4D4D4D"
COL_ELD_LT = "#6BAED6"
COL_GREEN = "#2E8B57"
COL_ORANGE = "#E6550D"

# =============================================================================
# LOAD SOURCE DATA
# =============================================================================
print("Loading source data...")

pymc_results = pd.read_csv(os.path.join(tables, "table_pymc_results.csv"))
pymc_convergence = pd.read_csv(os.path.join(tables, "table_pymc_convergence.csv"))
brms_vs_pymc = pd.read_csv(os.path.join(tables, "table_brms_vs_pymc.csv"))

# Current brms tables (to archive)
table2_current = pd.read_csv(os.path.join(tables, "table2_primary_results.csv"))
table3_current = pd.read_csv(os.path.join(tables, "table3_tier2_effectiveness.csv"))

# Tier 3 (stays as brms, not changed)
tier3 = pd.read_csv(os.path.join(tables, "table4_tier3_superiority.csv"))

# =============================================================================
# PART A: TABLE UPDATES
# =============================================================================
print("\n=== UPDATING TABLES ===")

# --- Archive current brms tables as sensitivity ---
print("Creating table_brms_sensitivity.csv...")
brms_sensitivity = brms_vs_pymc[['Outcome', 'brms_ATE', 'brms_CrI_lo', 'brms_CrI_hi',
                                  'brms_P_NI', 'brms_N_gcomp']].copy()
brms_sensitivity.columns = ['Outcome', 'ATE', 'CrI_lo', 'CrI_hi', 'P_NI', 'N_gcomp']
brms_sensitivity['Framework'] = 'brms (supplementary)'
brms_sensitivity.to_csv(os.path.join(tables, "table_brms_sensitivity.csv"), index=False)
print(f"  Saved: {os.path.join(tables, 'table_brms_sensitivity.csv')}")

# --- Rewrite table2_primary_results.csv with PyMC values ---
print("Rewriting table2_primary_results.csv with PyMC values...")
pymc_primary = pymc_results[pymc_results['Outcome'] == 'ODI 3 months'].iloc[0]

# Read sample sizes from actual data
df_full = pd.read_csv(os.path.join(base_dir, "data", "df_disc_full.csv"))
n_eld = int((df_full['treatment_num'] == 1).sum())
n_msd = int((df_full['treatment_num'] == 0).sum())

table2_new = pd.DataFrame([{
    'Outcome': 'ODI 3 months',
    'Population': 'Disc herniation',
    'N_ELD': n_eld,
    'N_MSD': n_msd,
    'ATE': round(pymc_primary['ATE'], 4),
    '95% CrI': f"[{pymc_primary['CrI_lo']:.2f}, {pymc_primary['CrI_hi']:.2f}]",
    'P(NI)': f"{pymc_primary['P_NI']:.3f}",
    'P(Superiority)': f"{pymc_primary['P_Superiority']:.3f}",
    'NI_Margin': '7 ODI',
    'Conclusion': 'Non-inferior'
}])
table2_new.to_csv(os.path.join(tables, "table2_primary_results.csv"), index=False)
print(f"  ATE: {pymc_primary['ATE']:.4f} -> [{pymc_primary['CrI_lo']:.2f}, {pymc_primary['CrI_hi']:.2f}]")

# --- Rewrite table3_tier2_effectiveness.csv with PyMC values ---
print("Rewriting table3_tier2_effectiveness.csv with PyMC values...")

# Map PyMC outcome names to table3 format
name_map = {
    'ODI 12 months': 'ODI 12 months',
    'NRS back 3 months': 'NRS back pain 3 months',
    'NRS back 12 months': 'NRS back pain 12 months',
    'NRS leg 3 months': 'NRS leg pain 3 months',
    'NRS leg 12 months': 'NRS leg pain 12 months',
    'EQ-5D 3 months': 'EQ-5D 3 months',
    'EQ-5D 12 months': 'EQ-5D 12 months',
    'Responder 3 months': 'Responder 3 months (>=30% or >=10pt)',
    'RTW 3 months': 'Return to work 3 months',
    'RTW 12 months': 'Return to work 12 months',
    'Analgesic 3 months': 'Analgesic use 3 months',
    'Analgesic 12 months': 'Analgesic use 12 months',
    'Satisfaction 3 months': 'Satisfaction 3 months',
    'Satisfaction 12 months': 'Satisfaction 12 months',
    'GPE 3 months': 'GPE success 3 months',
    'GPE 12 months': 'GPE success 12 months',
}

table3_rows = []
for _, row in pymc_results.iterrows():
    if row['Outcome'] == 'ODI 3 months':
        continue  # Primary outcome in table2
    outcome_name = name_map.get(row['Outcome'], row['Outcome'])
    timepoint = '12m' if '12' in row['Outcome'] else '3m'
    table3_rows.append({
        'Outcome': outcome_name,
        'Timepoint': timepoint,
        'N': int(row['N_gcomp']),
        'ATE': row['ATE'],
        'CrI_lo': row['CrI_lo'],
        'CrI_hi': row['CrI_hi'],
        'P_NI': row['P_NI'],
        'P_Superiority': row['P_Superiority'],
        'NI_Margin': row['NI_Margin'],
        'NI_Conclusion': row['NI_Conclusion'],
        'Convergence': row['Convergence'],
    })

table3_new = pd.DataFrame(table3_rows)
table3_new.to_csv(os.path.join(tables, "table3_tier2_effectiveness.csv"), index=False)
print(f"  Updated {len(table3_rows)} rows with PyMC values")
print(f"  N_gcomp: 3m={421}, 12m={254} (was complete-case N before)")

# --- Export PyMC ATE draws as CSV for R script ---
print("Exporting PyMC ATE draws to CSV for R figure generation...")
ate_draws = np.load(os.path.join(models, "pymc_ate_odi_3m.npy"))
pd.DataFrame({'ate': ate_draws}).to_csv(
    os.path.join(tables, "pymc_ate_odi_3m_draws.csv"), index=False)
print(f"  Saved: {os.path.join(tables, 'pymc_ate_odi_3m_draws.csv')} ({len(ate_draws)} draws)")

# =============================================================================
# PART B: FIGURE GENERATION (S9, S11 only; Figures 2 & 3 use R/ggplot2)
# =============================================================================
print("\n=== GENERATING SUPPLEMENTARY FIGURES (S9, S11) ===")

# Matplotlib defaults for publication quality
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.sans-serif': ['Helvetica', 'Arial', 'DejaVu Sans'],
    'font.size': 11,
    'axes.labelsize': 11,
    'axes.titlesize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'figure.dpi': 300,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'savefig.facecolor': 'white',
    'axes.facecolor': 'white',
    'figure.facecolor': 'white',
})


# =============================================================================
# FIGURE S9: PyMC MCMC Diagnostics
# =============================================================================
print("Generating Figure S9: PyMC MCMC diagnostics...")

fig_s9, axes_s9 = plt.subplots(2, 2, figsize=(14, 10))

# Panel A: Trace plots for 4 key outcomes
ax_trace = axes_s9[0, 0]
key_outcomes = [
    ('ODI 3 months', 'pymc_idata_odi_3m.nc'),
    ('NRS back 3m', 'pymc_idata_nrs_back_3m.nc'),
    ('EQ-5D 3m', 'pymc_idata_eq5d_3m.nc'),
    ('Responder 3m', 'pymc_idata_responder_3m.nc'),
]

trace_colors = [COL_ELD, COL_MSD, COL_GREEN, COL_ORANGE]
for idx, (name, fname) in enumerate(key_outcomes):
    fpath = os.path.join(models, fname)
    if os.path.exists(fpath):
        idata = az.from_netcdf(fpath)
        # Get beta_treatment from posterior
        if 'posterior' in idata.groups():
            post = idata.posterior
            # Find treatment variable
            treatment_var = None
            for var in post.data_vars:
                if 'treatment' in var.lower() or var == 'beta_treatment':
                    treatment_var = var
                    break
            if treatment_var is None:
                # Try beta[0] or similar
                for var in post.data_vars:
                    if 'beta' in var.lower():
                        treatment_var = var
                        break
            if treatment_var is not None:
                vals = post[treatment_var].values
                if vals.ndim == 2:
                    # (chain, draw) - plot each chain
                    for c in range(min(4, vals.shape[0])):
                        ax_trace.plot(vals[c, :], alpha=0.35, linewidth=0.3,
                                      color=trace_colors[idx])
                elif vals.ndim == 3:
                    # (chain, draw, param) - take first param
                    for c in range(min(4, vals.shape[0])):
                        ax_trace.plot(vals[c, :, 0], alpha=0.35, linewidth=0.3,
                                      color=trace_colors[idx])

# Legend for trace panel
trace_handles = [Line2D([0], [0], color=c, linewidth=1.5, label=n)
                 for (n, _), c in zip(key_outcomes, trace_colors)]
ax_trace.legend(handles=trace_handles, fontsize=8, loc='upper right',
                framealpha=0.9)
ax_trace.set_xlabel("Iteration", fontsize=10)
ax_trace.set_ylabel("beta_treatment", fontsize=10)
ax_trace.set_title("A  Trace plots (treatment coefficient)", fontsize=10.5,
                    fontweight='bold', loc='left')
ax_trace.spines['top'].set_visible(False)
ax_trace.spines['right'].set_visible(False)

# Panel B: Rhat distribution histogram
ax_rhat = axes_s9[0, 1]
rhat_vals = pymc_convergence['rhat_max'].values
ax_rhat.hist(rhat_vals, bins=15, color=COL_ELD, alpha=0.7, edgecolor='white',
             linewidth=0.5)
ax_rhat.axvline(1.01, color=COL_MSD, linestyle='--', linewidth=1,
                label='Rhat = 1.01 threshold')
ax_rhat.set_xlabel("Maximum Rhat", fontsize=10)
ax_rhat.set_ylabel("Count", fontsize=10)
ax_rhat.set_title("B  Rhat distribution across outcomes", fontsize=10.5,
                    fontweight='bold', loc='left')
ax_rhat.legend(fontsize=8, framealpha=0.9)
ax_rhat.spines['top'].set_visible(False)
ax_rhat.spines['right'].set_visible(False)

# Panel C: ESS bulk vs tail scatter
ax_ess = axes_s9[1, 0]
ess_bulk = pymc_convergence['ess_bulk_min'].values
ess_tail = pymc_convergence['ess_tail_min'].values
valid = pymc_convergence['valid'].values

colors_ess = [COL_ELD if v else COL_MSD for v in valid]
ax_ess.scatter(ess_bulk, ess_tail, c=colors_ess, s=50, alpha=0.8, zorder=3,
               edgecolors='white', linewidth=0.5)

# Label each point
for i, row in pymc_convergence.iterrows():
    short_name = row['outcome'].replace(' months', 'm').replace(' ', '\n')
    ax_ess.annotate(short_name, (row['ess_bulk_min'], row['ess_tail_min']),
                    fontsize=5.5, ha='center', va='bottom',
                    xytext=(0, 5), textcoords='offset points',
                    color='0.35')

# Threshold lines
ax_ess.axhline(400, color='0.60', linestyle=':', linewidth=0.8,
               label='ESS = 400')
ax_ess.axvline(400, color='0.60', linestyle=':', linewidth=0.8)

legend_handles = [
    Line2D([0], [0], marker='o', color='w', markerfacecolor=COL_ELD,
           markersize=8, label='Valid'),
    Line2D([0], [0], marker='o', color='w', markerfacecolor=COL_MSD,
           markersize=8, label='Issue'),
    Line2D([0], [0], color='0.60', linestyle=':', linewidth=0.8,
           label='ESS = 400'),
]
ax_ess.legend(handles=legend_handles, fontsize=8, loc='upper left',
              framealpha=0.9)
ax_ess.set_xlabel("ESS bulk (minimum)", fontsize=10)
ax_ess.set_ylabel("ESS tail (minimum)", fontsize=10)
ax_ess.set_title("C  Effective sample size: bulk vs. tail", fontsize=10.5,
                  fontweight='bold', loc='left')
ax_ess.spines['top'].set_visible(False)
ax_ess.spines['right'].set_visible(False)

# Panel D: Divergence summary bar chart
ax_div = axes_s9[1, 1]
outcomes_short = [o.replace(' months', 'm') for o in pymc_convergence['outcome']]
n_div = pymc_convergence['n_divergent'].values
bar_colors = [COL_MSD if d > 0 else COL_ELD for d in n_div]

bars = ax_div.barh(range(len(outcomes_short)), n_div, color=bar_colors,
                   alpha=0.8, edgecolor='white', linewidth=0.5)
ax_div.set_yticks(range(len(outcomes_short)))
ax_div.set_yticklabels(outcomes_short, fontsize=7.5)
ax_div.set_xlabel("Number of divergent transitions", fontsize=10)
ax_div.set_title("D  Divergent transitions by outcome", fontsize=10.5,
                  fontweight='bold', loc='left')

# Annotate counts on bars
for i, v in enumerate(n_div):
    if v > 0:
        ax_div.text(v + 2, i, str(v), va='center', fontsize=8, color=COL_MSD)

ax_div.spines['top'].set_visible(False)
ax_div.spines['right'].set_visible(False)

fig_s9.suptitle("PyMC MCMC Diagnostics", fontsize=13, fontweight='bold', y=1.01)
fig_s9.tight_layout()

s9_path = os.path.join(pub_dir, "Figure_S9_mcmc_diagnostics.png")
fig_s9.savefig(s9_path, dpi=300, bbox_inches='tight', facecolor='white')
fig_s9.savefig(os.path.join(fig_dir, "Figure_S9_mcmc_diagnostics.png"),
               dpi=300, bbox_inches='tight', facecolor='white')
plt.close(fig_s9)
print(f"  Saved: {s9_path}")


# =============================================================================
# FIGURE S11: brms vs PyMC comparison forest plot
# =============================================================================
print("Generating Figure S11: brms vs PyMC comparison...")

fig_s11, (ax_cont, ax_bin) = plt.subplots(1, 2, figsize=(14, 10))

# Separate continuous and binary outcomes
cont_outcomes = brms_vs_pymc[brms_vs_pymc['Outcome'].str.contains(
    'ODI|NRS|EQ-5D', case=False)].copy()
bin_outcomes = brms_vs_pymc[~brms_vs_pymc['Outcome'].str.contains(
    'ODI|NRS|EQ-5D', case=False)].copy()

# Shorten labels
def shorten_label(s):
    s = s.replace(' months', 'm')
    s = s.replace(' pain', '')
    s = s.replace('success ', '')
    s = s.replace(' (>=30% or >=10pt)', '')
    s = s.replace('Return to work', 'RTW')
    s = s.replace('Analgesic use', 'Analgesic')
    s = s.replace('GPE success', 'GPE')
    return s

def draw_comparison_panel(ax, df, panel_label, fmt_str=".2f"):
    df = df.iloc[::-1].reset_index(drop=True)  # Reverse for bottom-up
    n = len(df)
    offset = 0.12

    # Find x range for annotation positioning
    all_hi = max(df['brms_CrI_hi'].max(), df['PyMC_CrI_hi'].max())
    all_lo = min(df['brms_CrI_lo'].min(), df['PyMC_CrI_lo'].min())
    x_range = all_hi - all_lo
    annot_x = all_hi + x_range * 0.06

    for i, row in df.iterrows():
        # brms (blue circles, offset down)
        ax.errorbar(row['brms_ATE'], i - offset,
                    xerr=[[row['brms_ATE'] - row['brms_CrI_lo']],
                          [row['brms_CrI_hi'] - row['brms_ATE']]],
                    fmt='o', color=COL_ELD, markersize=5,
                    elinewidth=0.7, capsize=2, capthick=0.7, zorder=4)

        # PyMC (orange squares, offset up)
        ax.errorbar(row['PyMC_ATE'], i + offset,
                    xerr=[[row['PyMC_ATE'] - row['PyMC_CrI_lo']],
                          [row['PyMC_CrI_hi'] - row['PyMC_ATE']]],
                    fmt='s', color=COL_ORANGE, markersize=5,
                    elinewidth=0.7, capsize=2, capthick=0.7, zorder=4)

        # N_gcomp annotation (only show if different)
        brms_n = int(row['brms_N_gcomp'])
        pymc_n = int(row['PyMC_N_gcomp'])
        if brms_n != pymc_n:
            n_text = f"N: {brms_n}/{pymc_n}"
        else:
            n_text = f"N={brms_n}"

        # Right-side text annotation in data coordinates
        ax.text(annot_x, i, n_text, fontsize=7, color='0.40',
                va='center', ha='left', zorder=10)

    ax.axvline(0, linestyle='-', color='0.50', linewidth=0.4, zorder=1)

    labels = [shorten_label(row['Outcome']) for _, row in df.iterrows()]
    ax.set_yticks(range(n))
    ax.set_yticklabels(labels, fontsize=9)
    ax.set_ylim(-0.6, n - 0.4)

    ax.set_title(panel_label, fontsize=10.5, fontweight='bold', loc='left')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Expand x axis for annotations
    ax.set_xlim(all_lo - x_range * 0.05, annot_x + x_range * 0.35)

    # Legend
    handles = [
        Line2D([0], [0], marker='o', color=COL_ELD, linestyle='-',
               markersize=6, linewidth=0.7, label='brms'),
        Line2D([0], [0], marker='s', color=COL_ORANGE, linestyle='-',
               markersize=6, linewidth=0.7, label='PyMC'),
    ]
    ax.legend(handles=handles, fontsize=9, loc='lower right', framealpha=0.9)

# Panel A: Continuous
draw_comparison_panel(ax_cont, cont_outcomes,
                      "A  Continuous outcomes",
                      fmt_str=".2f")
ax_cont.set_xlabel("ATE (original scale, positive = favors ELD)", fontsize=10)

# Panel B: Binary
draw_comparison_panel(ax_bin, bin_outcomes,
                      "B  Binary outcomes (risk difference)",
                      fmt_str=".3f")
ax_bin.set_xlabel("ATE (risk difference, positive = favors ELD)", fontsize=10)

fig_s11.suptitle("Cross-Framework Concordance: brms vs. PyMC",
                 fontsize=13, fontweight='bold', y=1.01)

n_concordant = (brms_vs_pymc['Concordance'] == 'Concordant').sum()
n_total_bvp = len(brms_vs_pymc)
fig_s11.text(0.5, -0.02,
             f"{n_concordant}/{n_total_bvp} outcomes show concordant non-inferiority conclusions across frameworks. "
             "PyMC uses observed-case likelihoods with G-computation over the full analysis sample; "
             "brms uses complete-case analysis for non-Gaussian families.",
             fontsize=8.5, color='0.45', ha='center', wrap=True)

fig_s11.tight_layout()

s11_path = os.path.join(pub_dir, "Figure_S11_brms_vs_pymc.png")
fig_s11.savefig(s11_path, dpi=300, bbox_inches='tight', facecolor='white')
fig_s11.savefig(os.path.join(fig_dir, "Figure_S11_brms_vs_pymc.png"),
                dpi=300, bbox_inches='tight', facecolor='white')
plt.close(fig_s11)
print(f"  Saved: {s11_path}")


# =============================================================================
# PART C: VERIFICATION
# =============================================================================
print("\n=== VERIFICATION ===")

# Check table2
t2_check = pd.read_csv(os.path.join(tables, "table2_primary_results.csv"))
print(f"Table 2 ATE: {t2_check['ATE'].iloc[0]}")
print(f"Table 2 CrI: {t2_check['95% CrI'].iloc[0]}")

# Check table3
t3_check = pd.read_csv(os.path.join(tables, "table3_tier2_effectiveness.csv"))
print(f"Table 3 rows: {len(t3_check)} (expected 16)")
print(f"Table 3 N values: {sorted(t3_check['N'].unique())} (expected [254, 421])")

# Check brms sensitivity
bs_check = pd.read_csv(os.path.join(tables, "table_brms_sensitivity.csv"))
print(f"brms sensitivity rows: {len(bs_check)} (expected 17)")

# Check figures (S9, S11 only; Figures 2 & 3 generated by R script)
for fname in ['Figure_S9_mcmc_diagnostics.png', 'Figure_S11_brms_vs_pymc.png']:
    fpath = os.path.join(pub_dir, fname)
    if os.path.exists(fpath):
        size_kb = os.path.getsize(fpath) / 1024
        print(f"  {fname}: {size_kb:.0f} KB")
    else:
        print(f"  {fname}: MISSING!")

print("\nDone.")
